### ISSUE TITLE
Team3 [1pt] Create basic structure for Dragons - Setup

### ISSUE THREAD

**Issue by VTY1999** [BereketRetta/reactSpaceTravelers#38]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.
- Project Link --- https://github.com/BereketRetta/reactSpaceTravelers/projects/1
- There are two-person in this project 
- Verissimo Francis and Bereket Retta

**Comment by dasileker** [comment]
### **Hi @BereketRetta,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
